package main.java.controller;

import main.java.entities.Billing;
import main.java.service.BillingService;

import java.util.List;

public class BillingController {
    private final BillingService billingService;

    // Constructor
    public BillingController() {
        this.billingService = new BillingService();
    }

    // Add a new bill
    public boolean addBill(int patientId, double amount, String billDate) {
        Billing billing = new Billing(0, patientId, amount, billDate); // ID is auto-generated by the database
        return billingService.addBill(billing);
    }

    // Update billing details
    public boolean updateBill(int id, int patientId, double amount, String billDate) {
        Billing billing = new Billing(id, patientId, amount, billDate);
        return billingService.updateBill(billing);
    }

    // Get billing information by ID
    public Billing getBillById(int id) {
        return billingService.getBillById(id);
    }

    // Get all billing records
    public List<Billing> getAllBills() {
        return billingService.getAllBills();
    }

    // Delete billing record by ID
    public boolean deleteBill(int id) {
        return billingService.deleteBill(id);
    }
}
